AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  TrustarGuarddutyintegration:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::106681964353:role/trustar_guard_duty_integration'
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.guardduty
      Environment:
        Variables:
          ENCLAVE_ID: 
          USER_API_KEY: 
          USER_API_SECRET:
      Tracing: Active
      ReservedConcurrentExecutions: 5
